services:
  mongodb:
    container_name: mongodb-apuestas-domino
    image: mongodb/mongodb-community-server:5.0.1-ubuntu2004
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: domino-dash

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/domino-dash
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:
